// 생성 파일 — 손으로 고치지 않는다.
//
// 국가 코드 선택지 전체(245). 출처: `phonenumbers` 9.0.39의 SUPPORTED_REGIONS(국가 번호가 있는
// 모든 지역)와 `pycountry` 26.2.16의 영어 이름. ISO 3166에 없는 세 지역(XK · AC · TA)은
// 이름을 직접 적었다. 국기는 ISO 두 글자 코드의 Regional Indicator 조합이다.
// 정렬은 영어 이름 순이다. 목록을 바꾸려면 같은 방식으로 다시 생성한다(2026-09-21).

import type { LoginCountry } from "./login";

export const loginCountries: readonly LoginCountry[] = [
  { id: "af", flag: "🇦🇫", name: "Afghanistan", dialCode: "+93" },
  { id: "al", flag: "🇦🇱", name: "Albania", dialCode: "+355" },
  { id: "dz", flag: "🇩🇿", name: "Algeria", dialCode: "+213" },
  { id: "as", flag: "🇦🇸", name: "American Samoa", dialCode: "+1" },
  { id: "ad", flag: "🇦🇩", name: "Andorra", dialCode: "+376" },
  { id: "ao", flag: "🇦🇴", name: "Angola", dialCode: "+244" },
  { id: "ai", flag: "🇦🇮", name: "Anguilla", dialCode: "+1" },
  { id: "ag", flag: "🇦🇬", name: "Antigua and Barbuda", dialCode: "+1" },
  { id: "ar", flag: "🇦🇷", name: "Argentina", dialCode: "+54" },
  { id: "am", flag: "🇦🇲", name: "Armenia", dialCode: "+374" },
  { id: "aw", flag: "🇦🇼", name: "Aruba", dialCode: "+297" },
  { id: "ac", flag: "🇦🇨", name: "Ascension Island", dialCode: "+247" },
  { id: "au", flag: "🇦🇺", name: "Australia", dialCode: "+61" },
  { id: "at", flag: "🇦🇹", name: "Austria", dialCode: "+43" },
  { id: "az", flag: "🇦🇿", name: "Azerbaijan", dialCode: "+994" },
  { id: "bs", flag: "🇧🇸", name: "Bahamas", dialCode: "+1" },
  { id: "bh", flag: "🇧🇭", name: "Bahrain", dialCode: "+973" },
  { id: "bd", flag: "🇧🇩", name: "Bangladesh", dialCode: "+880" },
  { id: "bb", flag: "🇧🇧", name: "Barbados", dialCode: "+1" },
  { id: "by", flag: "🇧🇾", name: "Belarus", dialCode: "+375" },
  { id: "be", flag: "🇧🇪", name: "Belgium", dialCode: "+32" },
  { id: "bz", flag: "🇧🇿", name: "Belize", dialCode: "+501" },
  { id: "bj", flag: "🇧🇯", name: "Benin", dialCode: "+229" },
  { id: "bm", flag: "🇧🇲", name: "Bermuda", dialCode: "+1" },
  { id: "bt", flag: "🇧🇹", name: "Bhutan", dialCode: "+975" },
  { id: "bo", flag: "🇧🇴", name: "Bolivia", dialCode: "+591" },
  { id: "bq", flag: "🇧🇶", name: "Bonaire, Sint Eustatius and Saba", dialCode: "+599" },
  { id: "ba", flag: "🇧🇦", name: "Bosnia and Herzegovina", dialCode: "+387" },
  { id: "bw", flag: "🇧🇼", name: "Botswana", dialCode: "+267" },
  { id: "br", flag: "🇧🇷", name: "Brazil", dialCode: "+55" },
  { id: "io", flag: "🇮🇴", name: "British Indian Ocean Territory", dialCode: "+246" },
  { id: "bn", flag: "🇧🇳", name: "Brunei Darussalam", dialCode: "+673" },
  { id: "bg", flag: "🇧🇬", name: "Bulgaria", dialCode: "+359" },
  { id: "bf", flag: "🇧🇫", name: "Burkina Faso", dialCode: "+226" },
  { id: "bi", flag: "🇧🇮", name: "Burundi", dialCode: "+257" },
  { id: "cv", flag: "🇨🇻", name: "Cabo Verde", dialCode: "+238" },
  { id: "kh", flag: "🇰🇭", name: "Cambodia", dialCode: "+855" },
  { id: "cm", flag: "🇨🇲", name: "Cameroon", dialCode: "+237" },
  { id: "ca", flag: "🇨🇦", name: "Canada", dialCode: "+1" },
  { id: "ky", flag: "🇰🇾", name: "Cayman Islands", dialCode: "+1" },
  { id: "cf", flag: "🇨🇫", name: "Central African Republic", dialCode: "+236" },
  { id: "td", flag: "🇹🇩", name: "Chad", dialCode: "+235" },
  { id: "cl", flag: "🇨🇱", name: "Chile", dialCode: "+56" },
  { id: "cn", flag: "🇨🇳", name: "China", dialCode: "+86" },
  { id: "cx", flag: "🇨🇽", name: "Christmas Island", dialCode: "+61" },
  { id: "cc", flag: "🇨🇨", name: "Cocos (Keeling) Islands", dialCode: "+61" },
  { id: "co", flag: "🇨🇴", name: "Colombia", dialCode: "+57" },
  { id: "km", flag: "🇰🇲", name: "Comoros", dialCode: "+269" },
  { id: "cg", flag: "🇨🇬", name: "Congo", dialCode: "+242" },
  { id: "cd", flag: "🇨🇩", name: "Congo, The Democratic Republic of the", dialCode: "+243" },
  { id: "ck", flag: "🇨🇰", name: "Cook Islands", dialCode: "+682" },
  { id: "cr", flag: "🇨🇷", name: "Costa Rica", dialCode: "+506" },
  { id: "hr", flag: "🇭🇷", name: "Croatia", dialCode: "+385" },
  { id: "cu", flag: "🇨🇺", name: "Cuba", dialCode: "+53" },
  { id: "cw", flag: "🇨🇼", name: "Curaçao", dialCode: "+599" },
  { id: "cy", flag: "🇨🇾", name: "Cyprus", dialCode: "+357" },
  { id: "cz", flag: "🇨🇿", name: "Czechia", dialCode: "+420" },
  { id: "ci", flag: "🇨🇮", name: "Côte d'Ivoire", dialCode: "+225" },
  { id: "dk", flag: "🇩🇰", name: "Denmark", dialCode: "+45" },
  { id: "dj", flag: "🇩🇯", name: "Djibouti", dialCode: "+253" },
  { id: "dm", flag: "🇩🇲", name: "Dominica", dialCode: "+1" },
  { id: "do", flag: "🇩🇴", name: "Dominican Republic", dialCode: "+1" },
  { id: "ec", flag: "🇪🇨", name: "Ecuador", dialCode: "+593" },
  { id: "eg", flag: "🇪🇬", name: "Egypt", dialCode: "+20" },
  { id: "sv", flag: "🇸🇻", name: "El Salvador", dialCode: "+503" },
  { id: "gq", flag: "🇬🇶", name: "Equatorial Guinea", dialCode: "+240" },
  { id: "er", flag: "🇪🇷", name: "Eritrea", dialCode: "+291" },
  { id: "ee", flag: "🇪🇪", name: "Estonia", dialCode: "+372" },
  { id: "sz", flag: "🇸🇿", name: "Eswatini", dialCode: "+268" },
  { id: "et", flag: "🇪🇹", name: "Ethiopia", dialCode: "+251" },
  { id: "fk", flag: "🇫🇰", name: "Falkland Islands (Malvinas)", dialCode: "+500" },
  { id: "fo", flag: "🇫🇴", name: "Faroe Islands", dialCode: "+298" },
  { id: "fj", flag: "🇫🇯", name: "Fiji", dialCode: "+679" },
  { id: "fi", flag: "🇫🇮", name: "Finland", dialCode: "+358" },
  { id: "fr", flag: "🇫🇷", name: "France", dialCode: "+33" },
  { id: "gf", flag: "🇬🇫", name: "French Guiana", dialCode: "+594" },
  { id: "pf", flag: "🇵🇫", name: "French Polynesia", dialCode: "+689" },
  { id: "ga", flag: "🇬🇦", name: "Gabon", dialCode: "+241" },
  { id: "gm", flag: "🇬🇲", name: "Gambia", dialCode: "+220" },
  { id: "ge", flag: "🇬🇪", name: "Georgia", dialCode: "+995" },
  { id: "de", flag: "🇩🇪", name: "Germany", dialCode: "+49" },
  { id: "gh", flag: "🇬🇭", name: "Ghana", dialCode: "+233" },
  { id: "gi", flag: "🇬🇮", name: "Gibraltar", dialCode: "+350" },
  { id: "gr", flag: "🇬🇷", name: "Greece", dialCode: "+30" },
  { id: "gl", flag: "🇬🇱", name: "Greenland", dialCode: "+299" },
  { id: "gd", flag: "🇬🇩", name: "Grenada", dialCode: "+1" },
  { id: "gp", flag: "🇬🇵", name: "Guadeloupe", dialCode: "+590" },
  { id: "gu", flag: "🇬🇺", name: "Guam", dialCode: "+1" },
  { id: "gt", flag: "🇬🇹", name: "Guatemala", dialCode: "+502" },
  { id: "gg", flag: "🇬🇬", name: "Guernsey", dialCode: "+44" },
  { id: "gn", flag: "🇬🇳", name: "Guinea", dialCode: "+224" },
  { id: "gw", flag: "🇬🇼", name: "Guinea-Bissau", dialCode: "+245" },
  { id: "gy", flag: "🇬🇾", name: "Guyana", dialCode: "+592" },
  { id: "ht", flag: "🇭🇹", name: "Haiti", dialCode: "+509" },
  { id: "va", flag: "🇻🇦", name: "Holy See (Vatican City State)", dialCode: "+39" },
  { id: "hn", flag: "🇭🇳", name: "Honduras", dialCode: "+504" },
  { id: "hk", flag: "🇭🇰", name: "Hong Kong", dialCode: "+852" },
  { id: "hu", flag: "🇭🇺", name: "Hungary", dialCode: "+36" },
  { id: "is", flag: "🇮🇸", name: "Iceland", dialCode: "+354" },
  { id: "in", flag: "🇮🇳", name: "India", dialCode: "+91" },
  { id: "id", flag: "🇮🇩", name: "Indonesia", dialCode: "+62" },
  { id: "ir", flag: "🇮🇷", name: "Iran", dialCode: "+98" },
  { id: "iq", flag: "🇮🇶", name: "Iraq", dialCode: "+964" },
  { id: "ie", flag: "🇮🇪", name: "Ireland", dialCode: "+353" },
  { id: "im", flag: "🇮🇲", name: "Isle of Man", dialCode: "+44" },
  { id: "il", flag: "🇮🇱", name: "Israel", dialCode: "+972" },
  { id: "it", flag: "🇮🇹", name: "Italy", dialCode: "+39" },
  { id: "jm", flag: "🇯🇲", name: "Jamaica", dialCode: "+1" },
  { id: "jp", flag: "🇯🇵", name: "Japan", dialCode: "+81" },
  { id: "je", flag: "🇯🇪", name: "Jersey", dialCode: "+44" },
  { id: "jo", flag: "🇯🇴", name: "Jordan", dialCode: "+962" },
  { id: "kz", flag: "🇰🇿", name: "Kazakhstan", dialCode: "+7" },
  { id: "ke", flag: "🇰🇪", name: "Kenya", dialCode: "+254" },
  { id: "ki", flag: "🇰🇮", name: "Kiribati", dialCode: "+686" },
  { id: "xk", flag: "🇽🇰", name: "Kosovo", dialCode: "+383" },
  { id: "kw", flag: "🇰🇼", name: "Kuwait", dialCode: "+965" },
  { id: "kg", flag: "🇰🇬", name: "Kyrgyzstan", dialCode: "+996" },
  { id: "la", flag: "🇱🇦", name: "Laos", dialCode: "+856" },
  { id: "lv", flag: "🇱🇻", name: "Latvia", dialCode: "+371" },
  { id: "lb", flag: "🇱🇧", name: "Lebanon", dialCode: "+961" },
  { id: "ls", flag: "🇱🇸", name: "Lesotho", dialCode: "+266" },
  { id: "lr", flag: "🇱🇷", name: "Liberia", dialCode: "+231" },
  { id: "ly", flag: "🇱🇾", name: "Libya", dialCode: "+218" },
  { id: "li", flag: "🇱🇮", name: "Liechtenstein", dialCode: "+423" },
  { id: "lt", flag: "🇱🇹", name: "Lithuania", dialCode: "+370" },
  { id: "lu", flag: "🇱🇺", name: "Luxembourg", dialCode: "+352" },
  { id: "mo", flag: "🇲🇴", name: "Macao", dialCode: "+853" },
  { id: "mg", flag: "🇲🇬", name: "Madagascar", dialCode: "+261" },
  { id: "mw", flag: "🇲🇼", name: "Malawi", dialCode: "+265" },
  { id: "my", flag: "🇲🇾", name: "Malaysia", dialCode: "+60" },
  { id: "mv", flag: "🇲🇻", name: "Maldives", dialCode: "+960" },
  { id: "ml", flag: "🇲🇱", name: "Mali", dialCode: "+223" },
  { id: "mt", flag: "🇲🇹", name: "Malta", dialCode: "+356" },
  { id: "mh", flag: "🇲🇭", name: "Marshall Islands", dialCode: "+692" },
  { id: "mq", flag: "🇲🇶", name: "Martinique", dialCode: "+596" },
  { id: "mr", flag: "🇲🇷", name: "Mauritania", dialCode: "+222" },
  { id: "mu", flag: "🇲🇺", name: "Mauritius", dialCode: "+230" },
  { id: "yt", flag: "🇾🇹", name: "Mayotte", dialCode: "+262" },
  { id: "mx", flag: "🇲🇽", name: "Mexico", dialCode: "+52" },
  { id: "fm", flag: "🇫🇲", name: "Micronesia, Federated States of", dialCode: "+691" },
  { id: "md", flag: "🇲🇩", name: "Moldova", dialCode: "+373" },
  { id: "mc", flag: "🇲🇨", name: "Monaco", dialCode: "+377" },
  { id: "mn", flag: "🇲🇳", name: "Mongolia", dialCode: "+976" },
  { id: "me", flag: "🇲🇪", name: "Montenegro", dialCode: "+382" },
  { id: "ms", flag: "🇲🇸", name: "Montserrat", dialCode: "+1" },
  { id: "ma", flag: "🇲🇦", name: "Morocco", dialCode: "+212" },
  { id: "mz", flag: "🇲🇿", name: "Mozambique", dialCode: "+258" },
  { id: "mm", flag: "🇲🇲", name: "Myanmar", dialCode: "+95" },
  { id: "na", flag: "🇳🇦", name: "Namibia", dialCode: "+264" },
  { id: "nr", flag: "🇳🇷", name: "Nauru", dialCode: "+674" },
  { id: "np", flag: "🇳🇵", name: "Nepal", dialCode: "+977" },
  { id: "nl", flag: "🇳🇱", name: "Netherlands", dialCode: "+31" },
  { id: "nc", flag: "🇳🇨", name: "New Caledonia", dialCode: "+687" },
  { id: "nz", flag: "🇳🇿", name: "New Zealand", dialCode: "+64" },
  { id: "ni", flag: "🇳🇮", name: "Nicaragua", dialCode: "+505" },
  { id: "ne", flag: "🇳🇪", name: "Niger", dialCode: "+227" },
  { id: "ng", flag: "🇳🇬", name: "Nigeria", dialCode: "+234" },
  { id: "nu", flag: "🇳🇺", name: "Niue", dialCode: "+683" },
  { id: "nf", flag: "🇳🇫", name: "Norfolk Island", dialCode: "+672" },
  { id: "kp", flag: "🇰🇵", name: "North Korea", dialCode: "+850" },
  { id: "mk", flag: "🇲🇰", name: "North Macedonia", dialCode: "+389" },
  { id: "mp", flag: "🇲🇵", name: "Northern Mariana Islands", dialCode: "+1" },
  { id: "no", flag: "🇳🇴", name: "Norway", dialCode: "+47" },
  { id: "om", flag: "🇴🇲", name: "Oman", dialCode: "+968" },
  { id: "pk", flag: "🇵🇰", name: "Pakistan", dialCode: "+92" },
  { id: "pw", flag: "🇵🇼", name: "Palau", dialCode: "+680" },
  { id: "ps", flag: "🇵🇸", name: "Palestine, State of", dialCode: "+970" },
  { id: "pa", flag: "🇵🇦", name: "Panama", dialCode: "+507" },
  { id: "pg", flag: "🇵🇬", name: "Papua New Guinea", dialCode: "+675" },
  { id: "py", flag: "🇵🇾", name: "Paraguay", dialCode: "+595" },
  { id: "pe", flag: "🇵🇪", name: "Peru", dialCode: "+51" },
  { id: "ph", flag: "🇵🇭", name: "Philippines", dialCode: "+63" },
  { id: "pl", flag: "🇵🇱", name: "Poland", dialCode: "+48" },
  { id: "pt", flag: "🇵🇹", name: "Portugal", dialCode: "+351" },
  { id: "pr", flag: "🇵🇷", name: "Puerto Rico", dialCode: "+1" },
  { id: "qa", flag: "🇶🇦", name: "Qatar", dialCode: "+974" },
  { id: "ro", flag: "🇷🇴", name: "Romania", dialCode: "+40" },
  { id: "ru", flag: "🇷🇺", name: "Russian Federation", dialCode: "+7" },
  { id: "rw", flag: "🇷🇼", name: "Rwanda", dialCode: "+250" },
  { id: "re", flag: "🇷🇪", name: "Réunion", dialCode: "+262" },
  { id: "bl", flag: "🇧🇱", name: "Saint Barthélemy", dialCode: "+590" },
  { id: "sh", flag: "🇸🇭", name: "Saint Helena, Ascension and Tristan da Cunha", dialCode: "+290" },
  { id: "kn", flag: "🇰🇳", name: "Saint Kitts and Nevis", dialCode: "+1" },
  { id: "lc", flag: "🇱🇨", name: "Saint Lucia", dialCode: "+1" },
  { id: "mf", flag: "🇲🇫", name: "Saint Martin (French part)", dialCode: "+590" },
  { id: "pm", flag: "🇵🇲", name: "Saint Pierre and Miquelon", dialCode: "+508" },
  { id: "vc", flag: "🇻🇨", name: "Saint Vincent and the Grenadines", dialCode: "+1" },
  { id: "ws", flag: "🇼🇸", name: "Samoa", dialCode: "+685" },
  { id: "sm", flag: "🇸🇲", name: "San Marino", dialCode: "+378" },
  { id: "st", flag: "🇸🇹", name: "Sao Tome and Principe", dialCode: "+239" },
  { id: "sa", flag: "🇸🇦", name: "Saudi Arabia", dialCode: "+966" },
  { id: "sn", flag: "🇸🇳", name: "Senegal", dialCode: "+221" },
  { id: "rs", flag: "🇷🇸", name: "Serbia", dialCode: "+381" },
  { id: "sc", flag: "🇸🇨", name: "Seychelles", dialCode: "+248" },
  { id: "sl", flag: "🇸🇱", name: "Sierra Leone", dialCode: "+232" },
  { id: "sg", flag: "🇸🇬", name: "Singapore", dialCode: "+65" },
  { id: "sx", flag: "🇸🇽", name: "Sint Maarten (Dutch part)", dialCode: "+1" },
  { id: "sk", flag: "🇸🇰", name: "Slovakia", dialCode: "+421" },
  { id: "si", flag: "🇸🇮", name: "Slovenia", dialCode: "+386" },
  { id: "sb", flag: "🇸🇧", name: "Solomon Islands", dialCode: "+677" },
  { id: "so", flag: "🇸🇴", name: "Somalia", dialCode: "+252" },
  { id: "za", flag: "🇿🇦", name: "South Africa", dialCode: "+27" },
  { id: "kr", flag: "🇰🇷", name: "South Korea", dialCode: "+82" },
  { id: "ss", flag: "🇸🇸", name: "South Sudan", dialCode: "+211" },
  { id: "es", flag: "🇪🇸", name: "Spain", dialCode: "+34" },
  { id: "lk", flag: "🇱🇰", name: "Sri Lanka", dialCode: "+94" },
  { id: "sd", flag: "🇸🇩", name: "Sudan", dialCode: "+249" },
  { id: "sr", flag: "🇸🇷", name: "Suriname", dialCode: "+597" },
  { id: "sj", flag: "🇸🇯", name: "Svalbard and Jan Mayen", dialCode: "+47" },
  { id: "se", flag: "🇸🇪", name: "Sweden", dialCode: "+46" },
  { id: "ch", flag: "🇨🇭", name: "Switzerland", dialCode: "+41" },
  { id: "sy", flag: "🇸🇾", name: "Syria", dialCode: "+963" },
  { id: "tw", flag: "🇹🇼", name: "Taiwan", dialCode: "+886" },
  { id: "tj", flag: "🇹🇯", name: "Tajikistan", dialCode: "+992" },
  { id: "tz", flag: "🇹🇿", name: "Tanzania", dialCode: "+255" },
  { id: "th", flag: "🇹🇭", name: "Thailand", dialCode: "+66" },
  { id: "tl", flag: "🇹🇱", name: "Timor-Leste", dialCode: "+670" },
  { id: "tg", flag: "🇹🇬", name: "Togo", dialCode: "+228" },
  { id: "tk", flag: "🇹🇰", name: "Tokelau", dialCode: "+690" },
  { id: "to", flag: "🇹🇴", name: "Tonga", dialCode: "+676" },
  { id: "tt", flag: "🇹🇹", name: "Trinidad and Tobago", dialCode: "+1" },
  { id: "ta", flag: "🇹🇦", name: "Tristan da Cunha", dialCode: "+290" },
  { id: "tn", flag: "🇹🇳", name: "Tunisia", dialCode: "+216" },
  { id: "tm", flag: "🇹🇲", name: "Turkmenistan", dialCode: "+993" },
  { id: "tc", flag: "🇹🇨", name: "Turks and Caicos Islands", dialCode: "+1" },
  { id: "tv", flag: "🇹🇻", name: "Tuvalu", dialCode: "+688" },
  { id: "tr", flag: "🇹🇷", name: "Türkiye", dialCode: "+90" },
  { id: "ug", flag: "🇺🇬", name: "Uganda", dialCode: "+256" },
  { id: "ua", flag: "🇺🇦", name: "Ukraine", dialCode: "+380" },
  { id: "ae", flag: "🇦🇪", name: "United Arab Emirates", dialCode: "+971" },
  { id: "gb", flag: "🇬🇧", name: "United Kingdom", dialCode: "+44" },
  { id: "us", flag: "🇺🇸", name: "United States", dialCode: "+1" },
  { id: "uy", flag: "🇺🇾", name: "Uruguay", dialCode: "+598" },
  { id: "uz", flag: "🇺🇿", name: "Uzbekistan", dialCode: "+998" },
  { id: "vu", flag: "🇻🇺", name: "Vanuatu", dialCode: "+678" },
  { id: "ve", flag: "🇻🇪", name: "Venezuela", dialCode: "+58" },
  { id: "vn", flag: "🇻🇳", name: "Vietnam", dialCode: "+84" },
  { id: "vg", flag: "🇻🇬", name: "Virgin Islands, British", dialCode: "+1" },
  { id: "vi", flag: "🇻🇮", name: "Virgin Islands, U.S.", dialCode: "+1" },
  { id: "wf", flag: "🇼🇫", name: "Wallis and Futuna", dialCode: "+681" },
  { id: "eh", flag: "🇪🇭", name: "Western Sahara", dialCode: "+212" },
  { id: "ye", flag: "🇾🇪", name: "Yemen", dialCode: "+967" },
  { id: "zm", flag: "🇿🇲", name: "Zambia", dialCode: "+260" },
  { id: "zw", flag: "🇿🇼", name: "Zimbabwe", dialCode: "+263" },
  { id: "ax", flag: "🇦🇽", name: "Åland Islands", dialCode: "+358" },
];
